//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"text/template"
	"unicode"

	"gopkg.in/yaml.v3"
)

type Field struct {
	Name    string `yaml:"name"`
	Type    string `yaml:"type"`
	Default string `yaml:"default"`
}

type Variable struct {
	Name    string  `yaml:"name"`
	Storage string  `yaml:"storage"`
	Type    string  `yaml:"type"`
	Default string  `yaml:"default"`
	Fields  []Field `yaml:"fields"`
}

func (v Variable) Key() string {
	return "Global_" + v.Name
}

func (v Variable) StructName() string {
	return v.Name + "_t"
}

func (v Variable) HasFields() bool {
	return len(v.Fields) > 0
}

type Registry struct {
	Variables []Variable `yaml:"variables"`
}

const stateTemplate = `
package core

import "vinyl-orchestrator/typedefs"

// ==========================================
// CODE GENERATED BY GO GENERATE; DO NOT EDIT.
// ==========================================

var StateRegistry = make(map[StateKey_t]StateMetadata)

type StorageMechanism int

const (
	NonVolatile StorageMechanism = iota
	Volatile
)

type StateMetadata struct {
	StorageType StorageMechanism
	DefaultData interface{}
}

type StateKey_t string

type TypedKey[T any] struct {
	Key StateKey_t
}

type OnDataSourceChangedArgs_t struct {
	Variable StateKey_t  {{tick}}json:"variable"{{tick}}
	Data     interface{} {{tick}}json:"data"{{tick}}
}

{{range .Variables}}
// ── {{.Name}} ──────────────────────────────────

{{if .HasFields}}
type {{.StructName}} struct {
{{range .Fields}}	{{.Name}} {{.Type}} {{tick}}json:"{{toJsonTag .Name}}"{{tick}}
{{end}}}
{{end}}

var Global_{{.Name}} = TypedKey[{{if .HasFields}}{{.StructName}}{{else}}{{.Type}}{{end}}]{Key: "{{.Key}}"}

func init() {
	StateRegistry[Global_{{.Name}}.Key] = StateMetadata{
		StorageType: {{.Storage}},
		{{if .HasFields}}DefaultData: {{.StructName}}{
{{range .Fields}}			{{.Name}}: {{.Default}},
{{end}}		},{{else}}DefaultData: {{.Type}}({{.Default}}),{{end}}
	}
}
{{end}}
`

func toJsonTag(s string) string {
	if len(s) == 0 {
		return ""
	}
	a := []rune(s)
	a[0] = unicode.ToLower(a[0])
	return string(a)
}

func main() {
	yamlFile, err := os.ReadFile("registry.yaml")
	if err != nil {
		log.Fatalf("Failed to read YAML: %v", err)
	}

	var registry Registry
	if err := yaml.Unmarshal(yamlFile, &registry); err != nil {
		log.Fatalf("Failed to parse YAML: %v", err)
	}

	tmpl, err := template.New("state").Funcs(template.FuncMap{
		"toJsonTag": toJsonTag,
		"tick":      func() string { return "`" },
	}).Parse(stateTemplate)
	if err != nil {
		log.Fatalf("Failed to parse template: %v", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, registry); err != nil {
		log.Fatalf("Failed to execute template: %v", err)
	}

	formattedCode, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Println("Warning: Could not format code. Writing raw template output.")
		formattedCode = buf.Bytes()
	}

	if err := os.WriteFile("state.go", formattedCode, 0644); err != nil {
		log.Fatalf("Failed to write state.go: %v", err)
	}

	fmt.Println("Successfully generated state.go from registry.yaml!")
}
