package core

import "vinyl-orchestrator/typedefs"

// ==========================================
// CODE GENERATED BY GO GENERATE; DO NOT EDIT.
// ==========================================

var StateRegistry = make(map[StateKey_t]StateMetadata)

type StorageMechanism int

const (
	NonVolatile StorageMechanism = iota
	Volatile
)

type StateMetadata struct {
	StorageType StorageMechanism
	DefaultData interface{}
}

// typeshare
type StateKey_t string

type TypedKey[T any] struct {
	Key StateKey_t
}

// typeshare
type OnDataSourceChangedArgs_t struct {
	Variable StateKey_t  `json:"variable"`
	Data     interface{} `json:"data"`
}

// ── MusicAssistantUrl ──────────────────────────────────

var Global_MusicAssistantUrl = TypedKey[string]{Key: "Global_MusicAssistantUrl"}

func init() {
	StateRegistry[Global_MusicAssistantUrl.Key] = StateMetadata{
		StorageType: NonVolatile,
		DefaultData: string(""),
	}
}

// ── MusicAssistantToken ──────────────────────────────────

var Global_MusicAssistantToken = TypedKey[string]{Key: "Global_MusicAssistantToken"}

func init() {
	StateRegistry[Global_MusicAssistantToken.Key] = StateMetadata{
		StorageType: NonVolatile,
		DefaultData: string(""),
	}
}

// ── MusicAssistantTargetPlayerId ──────────────────────────────────

var Global_MusicAssistantTargetPlayerId = TypedKey[string]{Key: "Global_MusicAssistantTargetPlayerId"}

func init() {
	StateRegistry[Global_MusicAssistantTargetPlayerId.Key] = StateMetadata{
		StorageType: NonVolatile,
		DefaultData: string(""),
	}
}

// ── FlutterWebUrl ──────────────────────────────────

var Global_FlutterWebUrl = TypedKey[string]{Key: "Global_FlutterWebUrl"}

func init() {
	StateRegistry[Global_FlutterWebUrl.Key] = StateMetadata{
		StorageType: NonVolatile,
		DefaultData: string(""),
	}
}

// ── FlutterWebPort ──────────────────────────────────

var Global_FlutterWebPort = TypedKey[string]{Key: "Global_FlutterWebPort"}

func init() {
	StateRegistry[Global_FlutterWebPort.Key] = StateMetadata{
		StorageType: NonVolatile,
		DefaultData: string(""),
	}
}

// ── MqttBrokerHostAddress ──────────────────────────────────

var Global_MqttBrokerHostAddress = TypedKey[string]{Key: "Global_MqttBrokerHostAddress"}

func init() {
	StateRegistry[Global_MqttBrokerHostAddress.Key] = StateMetadata{
		StorageType: NonVolatile,
		DefaultData: string("127.0.0.1"),
	}
}

// ── MqttWebSocketPort ──────────────────────────────────

var Global_MqttWebSocketPort = TypedKey[int]{Key: "Global_MqttWebSocketPort"}

func init() {
	StateRegistry[Global_MqttWebSocketPort.Key] = StateMetadata{
		StorageType: NonVolatile,
		DefaultData: int(9001),
	}
}

// ── MqttTcpPort ──────────────────────────────────

var Global_MqttTcpPort = TypedKey[int]{Key: "Global_MqttTcpPort"}

func init() {
	StateRegistry[Global_MqttTcpPort.Key] = StateMetadata{
		StorageType: NonVolatile,
		DefaultData: int(1883),
	}
}

// ── LastKnownUidScanned ──────────────────────────────────

var Global_LastKnownUidScanned = TypedKey[string]{Key: "Global_LastKnownUidScanned"}

func init() {
	StateRegistry[Global_LastKnownUidScanned.Key] = StateMetadata{
		StorageType: Volatile,
		DefaultData: string(""),
	}
}

// ── LastUnknownUidScanned ──────────────────────────────────

var Global_LastUnknownUidScanned = TypedKey[string]{Key: "Global_LastUnknownUidScanned"}

func init() {
	StateRegistry[Global_LastUnknownUidScanned.Key] = StateMetadata{
		StorageType: Volatile,
		DefaultData: string(""),
	}
}

// ── CurrentShelfStatus ──────────────────────────────────

var Global_CurrentShelfStatus = TypedKey[typedefs.ShelfStatus_t]{Key: "Global_CurrentShelfStatus"}

func init() {
	StateRegistry[Global_CurrentShelfStatus.Key] = StateMetadata{
		StorageType: Volatile,
		DefaultData: typedefs.ShelfStatus_t(typedefs.ShelfStatus_Empty),
	}
}

// ── ReaderConnectionStatus ──────────────────────────────────

var Global_ReaderConnectionStatus = TypedKey[typedefs.ReaderStatus_t]{Key: "Global_ReaderConnectionStatus"}

func init() {
	StateRegistry[Global_ReaderConnectionStatus.Key] = StateMetadata{
		StorageType: Volatile,
		DefaultData: typedefs.ReaderStatus_t(typedefs.ReaderStatus_Offline),
	}
}

// ── CurrentProjectorData ──────────────────────────────────

var Global_CurrentProjectorData = TypedKey[typedefs.ProjectorData_t]{Key: "Global_CurrentProjectorData"}

func init() {
	StateRegistry[Global_CurrentProjectorData.Key] = StateMetadata{
		StorageType: Volatile,
		DefaultData: typedefs.ProjectorData_t(typedefs.ProjectorData_t{VisualDataState: typedefs.VisualDataState_DisplayIdle}),
	}
}

// ── ProjectorHeartbeatSignal ──────────────────────────────────

var Global_ProjectorHeartbeatSignal = TypedKey[interface{}]{Key: "Global_ProjectorHeartbeatSignal"}

func init() {
	StateRegistry[Global_ProjectorHeartbeatSignal.Key] = StateMetadata{
		StorageType: Volatile,
		DefaultData: interface{}(nil),
	}
}

// ── DefinedProjectorErrorMessage ──────────────────────────────────

var Global_DefinedProjectorErrorMessage = TypedKey[string]{Key: "Global_DefinedProjectorErrorMessage"}

func init() {
	StateRegistry[Global_DefinedProjectorErrorMessage.Key] = StateMetadata{
		StorageType: Volatile,
		DefaultData: string(""),
	}
}

// ── ProjectorHeartbeat ──────────────────────────────────

var Global_ProjectorHeartbeat = TypedKey[interface{}]{Key: "Global_ProjectorHeartbeat"}

func init() {
	StateRegistry[Global_ProjectorHeartbeat.Key] = StateMetadata{
		StorageType: Volatile,
		DefaultData: interface{}(nil),
	}
}

// ── TargetDisplayWidthInPixels ──────────────────────────────────

var Global_TargetDisplayWidthInPixels = TypedKey[string]{Key: "Global_TargetDisplayWidthInPixels"}

func init() {
	StateRegistry[Global_TargetDisplayWidthInPixels.Key] = StateMetadata{
		StorageType: NonVolatile,
		DefaultData: string("1920"),
	}
}

// ── TargetDisplayHeightInPixels ──────────────────────────────────

var Global_TargetDisplayHeightInPixels = TypedKey[string]{Key: "Global_TargetDisplayHeightInPixels"}

func init() {
	StateRegistry[Global_TargetDisplayHeightInPixels.Key] = StateMetadata{
		StorageType: NonVolatile,
		DefaultData: string("1080"),
	}
}

// ── CurrentMaptasticProjectorPositions ──────────────────────────────────

var Global_CurrentMaptasticProjectorPositions = TypedKey[string]{Key: "Global_CurrentMaptasticProjectorPositions"}

func init() {
	StateRegistry[Global_CurrentMaptasticProjectorPositions.Key] = StateMetadata{
		StorageType: NonVolatile,
		DefaultData: string(""),
	}
}

// ── SavedMaptasticProjectorPositions ──────────────────────────────────

var Global_SavedMaptasticProjectorPositions = TypedKey[string]{Key: "Global_SavedMaptasticProjectorPositions"}

func init() {
	StateRegistry[Global_SavedMaptasticProjectorPositions.Key] = StateMetadata{
		StorageType: NonVolatile,
		DefaultData: string(""),
	}
}

// ── MediaPlaybackState ──────────────────────────────────

var Global_MediaPlaybackState = TypedKey[typedefs.MediaPlaybackState_t]{Key: "Global_MediaPlaybackState"}

func init() {
	StateRegistry[Global_MediaPlaybackState.Key] = StateMetadata{
		StorageType: Volatile,
		DefaultData: typedefs.MediaPlaybackState_t(typedefs.PlayerState_Idle),
	}
}

// ── ActiveRecordTrackName ──────────────────────────────────

var Global_ActiveRecordTrackName = TypedKey[string]{Key: "Global_ActiveRecordTrackName"}

func init() {
	StateRegistry[Global_ActiveRecordTrackName.Key] = StateMetadata{
		StorageType: Volatile,
		DefaultData: string("Unknown"),
	}
}

// ── ActiveTrackProgressInSeconds ──────────────────────────────────

var Global_ActiveTrackProgressInSeconds = TypedKey[float64]{Key: "Global_ActiveTrackProgressInSeconds"}

func init() {
	StateRegistry[Global_ActiveTrackProgressInSeconds.Key] = StateMetadata{
		StorageType: Volatile,
		DefaultData: float64(0.0),
	}
}

// ── ActiveTrackTotalDurationInSeconds ──────────────────────────────────

var Global_ActiveTrackTotalDurationInSeconds = TypedKey[float64]{Key: "Global_ActiveTrackTotalDurationInSeconds"}

func init() {
	StateRegistry[Global_ActiveTrackTotalDurationInSeconds.Key] = StateMetadata{
		StorageType: Volatile,
		DefaultData: float64(0.0),
	}
}
