package core

// ==========================================
// CODE GENERATED BY GO GENERATE; DO NOT EDIT.
// ==========================================

var StateRegistry = make(map[StateKey_t]StateMetadata)

type StorageMechanism int

const (
	NonVolatile StorageMechanism = iota
	Volatile
)

type StateMetadata struct {
	StorageType StorageMechanism
	DefaultData interface{}
}

// typeshare
type StateKey_t string

// typeshare
type OnDataSourceChangedArgs_t struct {
	Variable StateKey_t  `json:"variable"`
	Data     interface{} `json:"data"`
}

// ── MusicAssistantUrl ──────────────────────────────────

const Global_MusicAssistantUrl StateKey_t = "Global_MusicAssistantUrl"

func init() {
	StateRegistry[Global_MusicAssistantUrl] = StateMetadata{
		StorageType: NonVolatile,
		DefaultData: string(""),
	}
}

// ── MusicAssistantToken ──────────────────────────────────

const Global_MusicAssistantToken StateKey_t = "Global_MusicAssistantToken"

func init() {
	StateRegistry[Global_MusicAssistantToken] = StateMetadata{
		StorageType: NonVolatile,
		DefaultData: string(""),
	}
}

// ── MusicAssistantTargetPlayerId ──────────────────────────────────

const Global_MusicAssistantTargetPlayerId StateKey_t = "Global_MusicAssistantTargetPlayerId"

func init() {
	StateRegistry[Global_MusicAssistantTargetPlayerId] = StateMetadata{
		StorageType: NonVolatile,
		DefaultData: string(""),
	}
}

// ── FlutterWebUrl ──────────────────────────────────

const Global_FlutterWebUrl StateKey_t = "Global_FlutterWebUrl"

func init() {
	StateRegistry[Global_FlutterWebUrl] = StateMetadata{
		StorageType: NonVolatile,
		DefaultData: string("localhost"),
	}
}

// ── FlutterWebPort ──────────────────────────────────

const Global_FlutterWebPort StateKey_t = "Global_FlutterWebPort"

func init() {
	StateRegistry[Global_FlutterWebPort] = StateMetadata{
		StorageType: NonVolatile,
		DefaultData: string("8080"),
	}
}

// ── MqttBrokerHostAddress ──────────────────────────────────

const Global_MqttBrokerHostAddress StateKey_t = "Global_MqttBrokerHostAddress"

func init() {
	StateRegistry[Global_MqttBrokerHostAddress] = StateMetadata{
		StorageType: NonVolatile,
		DefaultData: string("127.0.0.1"),
	}
}

// ── MqttWebSocketPort ──────────────────────────────────

const Global_MqttWebSocketPort StateKey_t = "Global_MqttWebSocketPort"

func init() {
	StateRegistry[Global_MqttWebSocketPort] = StateMetadata{
		StorageType: NonVolatile,
		DefaultData: int(9001),
	}
}

// ── MqttTcpPort ──────────────────────────────────

const Global_MqttTcpPort StateKey_t = "Global_MqttTcpPort"

func init() {
	StateRegistry[Global_MqttTcpPort] = StateMetadata{
		StorageType: NonVolatile,
		DefaultData: int(1883),
	}
}

// ── CurrentUidScanned ──────────────────────────────────

const Global_CurrentUidScanned StateKey_t = "Global_CurrentUidScanned"

func init() {
	StateRegistry[Global_CurrentUidScanned] = StateMetadata{
		StorageType: Volatile,
		DefaultData: string(""),
	}
}

// ── LastUnknownNfcTag ──────────────────────────────────

const Global_LastUnknownNfcTag StateKey_t = "Global_LastUnknownNfcTag"

func init() {
	StateRegistry[Global_LastUnknownNfcTag] = StateMetadata{
		StorageType: Volatile,
		DefaultData: string(""),
	}
}

// ── CurrentShelfStatus ──────────────────────────────────

const Global_CurrentShelfStatus StateKey_t = "Global_CurrentShelfStatus"

func init() {
	StateRegistry[Global_CurrentShelfStatus] = StateMetadata{
		StorageType: Volatile,
		DefaultData: ShelfStatus_t(ShelfStatus_Empty),
	}
}

// ── ReaderConnectionStatus ──────────────────────────────────

const Global_ReaderConnectionStatus StateKey_t = "Global_ReaderConnectionStatus"

func init() {
	StateRegistry[Global_ReaderConnectionStatus] = StateMetadata{
		StorageType: Volatile,
		DefaultData: string(""),
	}
}

// ── CurrentProjectorData ──────────────────────────────────

const Global_CurrentProjectorData StateKey_t = "Global_CurrentProjectorData"

func init() {
	StateRegistry[Global_CurrentProjectorData] = StateMetadata{
		StorageType: Volatile,
		DefaultData: ProjectorData_t(ProjectorData_t{PlayerState: PlayerState_Stopped}),
	}
}

// ── ProjectorHeartbeatSignal ──────────────────────────────────

const Global_ProjectorHeartbeatSignal StateKey_t = "Global_ProjectorHeartbeatSignal"

func init() {
	StateRegistry[Global_ProjectorHeartbeatSignal] = StateMetadata{
		StorageType: Volatile,
		DefaultData: interface{}(nil),
	}
}

// ── ProjectorHeartbeat ──────────────────────────────────

const Global_ProjectorHeartbeat StateKey_t = "Global_ProjectorHeartbeat"

func init() {
	StateRegistry[Global_ProjectorHeartbeat] = StateMetadata{
		StorageType: Volatile,
		DefaultData: interface{}(nil),
	}
}

// ── TargetDisplayWidthInPixels ──────────────────────────────────

const Global_TargetDisplayWidthInPixels StateKey_t = "Global_TargetDisplayWidthInPixels"

func init() {
	StateRegistry[Global_TargetDisplayWidthInPixels] = StateMetadata{
		StorageType: NonVolatile,
		DefaultData: string("1920"),
	}
}

// ── TargetDisplayHeightInPixels ──────────────────────────────────

const Global_TargetDisplayHeightInPixels StateKey_t = "Global_TargetDisplayHeightInPixels"

func init() {
	StateRegistry[Global_TargetDisplayHeightInPixels] = StateMetadata{
		StorageType: NonVolatile,
		DefaultData: string("1080"),
	}
}

// ── CurrentMaptasticProjectorPositions ──────────────────────────────────

const Global_CurrentMaptasticProjectorPositions StateKey_t = "Global_CurrentMaptasticProjectorPositions"

func init() {
	StateRegistry[Global_CurrentMaptasticProjectorPositions] = StateMetadata{
		StorageType: NonVolatile,
		DefaultData: string(""),
	}
}

// ── SavedMaptasticProjectorPositions ──────────────────────────────────

const Global_SavedMaptasticProjectorPositions StateKey_t = "Global_SavedMaptasticProjectorPositions"

func init() {
	StateRegistry[Global_SavedMaptasticProjectorPositions] = StateMetadata{
		StorageType: NonVolatile,
		DefaultData: string(""),
	}
}

// ── ActiveRecordPlaybackState ──────────────────────────────────

const Global_ActiveRecordPlaybackState StateKey_t = "Global_ActiveRecordPlaybackState"

func init() {
	StateRegistry[Global_ActiveRecordPlaybackState] = StateMetadata{
		StorageType: Volatile,
		DefaultData: string("idle"),
	}
}

// ── ActiveRecordTrackName ──────────────────────────────────

const Global_ActiveRecordTrackName StateKey_t = "Global_ActiveRecordTrackName"

func init() {
	StateRegistry[Global_ActiveRecordTrackName] = StateMetadata{
		StorageType: Volatile,
		DefaultData: string("Unknown"),
	}
}

// ── ActiveTrackProgressInSeconds ──────────────────────────────────

const Global_ActiveTrackProgressInSeconds StateKey_t = "Global_ActiveTrackProgressInSeconds"

func init() {
	StateRegistry[Global_ActiveTrackProgressInSeconds] = StateMetadata{
		StorageType: Volatile,
		DefaultData: float64(0.0),
	}
}

// ── ActiveTrackTotalDurationInSeconds ──────────────────────────────────

const Global_ActiveTrackTotalDurationInSeconds StateKey_t = "Global_ActiveTrackTotalDurationInSeconds"

func init() {
	StateRegistry[Global_ActiveTrackTotalDurationInSeconds] = StateMetadata{
		StorageType: Volatile,
		DefaultData: float64(0.0),
	}
}
