name: web_app
description: "Web app to manage NFC tags on vinyl records."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0-196.0.dev

dependencies:
  flutter:
    sdk: flutter
  app_links: ^6.0.0
  http: ^1.2.2
  mqtt_client: ^10.0.0
  file_picker: ^8.1.2
  flutter_colorpicker: ^1.1.0
  mime: ^2.0.0
  provider: ^6.1.1
  shared_preferences: ^2.3.2

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true